services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
  
  frontend:
    build:
      context: .
      dockerfile: scraper_front_end/Dockerfile
    volumes:
      - ./scraper_front_end:/app
    ports:
      - "80:80"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
